name: "Happy Birthday"
description: "Tells users happy birthday"
author: "pvinis@gmail.com"

runs:
  using: "node12"
  main: "index.js"

branding:
  icon: "loader"
  color: "purple"

inputs:
  github-token:
    description: "Github token"
    required: true
