name: A workflow to run my own action
on: [issues]

jobs:
  test:
    name: Happy birthday action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: yarn install
      - uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
