name: A workflow to run my own action
on: [issues]

jobs:
  test:
    name: Happy birthday action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
