name: A workflow to run my own action
on:
  issues:
    types: [opened, edited, reopened, closed]
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [opened, edited, reopened, closed]
  pull_request_review:
    types: [submitted, edited]
  pull_request_review_comment:
    types: [created, edited]

jobs:
  test:
    name: Happy birthday action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: yarn install
      - uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
